name: dio_nexus
description: NetworkManager for Flutter
version: 0.3.3+2

homepage: https://github.com/safauludogan/dio_nexus

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  dio: ^5.9.0

  # Utility
  retry: ^3.1.2
  connectivity_plus: ^7.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  fluttertoast: ^9.0.0
  logger: ^2.6.2

  # Other
  freezed_annotation: ^3.1.0
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  very_good_analysis: ^10.0.0
  
